Create list recommendations feature page
American-Capstones/TAMU-Spring-2022 pull request #22
Opened 2022-03-01 19:17 UTC by brianshao-prog

### Pre-Requisites

- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevant code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

### Description of Changes

Within web\src\pages\recommendations, created a recommendations page to display dummy links from links.json, made recommendation component module css to make unordered lists unbulleted

### Related Issues

Related to issue #8

2022-03-08 16:02 UTC, Ulfingrad requested changes
Great start! Dre and I will give it another passthrough once these changes are made

2022-03-08 16:02 UTC, Ulfingrad commented on packages/web/src/pages/recommendations/index.tsx
> +
```suggestion
```

2022-03-08 16:02 UTC, Ulfingrad commented on packages/web/src/pages/recommendations/index.tsx
> +
```suggestion
```

2022-03-10 18:03 UTC, brianshao-prog commented on packages/web/src/pages/recommendations/index.tsx
> +        </HStack>
Will keep it in for now

2022-03-10 18:04 UTC, brianshao-prog commented on packages/web/src/pages/recommendations/index.tsx
> +        </Text>
Will keep it in for now, just need to merge in the code in order to progress with rest of the team

2022-03-10 18:06 UTC, gageayk approved these changes
Good to go for now, testing will be fixed after workshop.

2022-03-10 18:08 UTC, merged